// The languages Gemini Live Translate accepts as `targetLanguageCode`, taken
// from https://ai.google.dev/gemini-api/docs/live-api/live-translate. Codes are
// BCP-47 and unrelated to the Deepgram/DeepL codes in LANGUAGE_OPTIONS, so the
// two lists stay separate rather than growing a fourth column.
export const GEMINI_LANGUAGE_OPTIONS = [
  // The four the extension is most likely to be pointed at come first; the rest
  // follow Google's own alphabetical-by-English-name order.
  { code: 'zh-Hant', label: '繁體中文' },
  { code: 'en', label: 'English' },
  { code: 'ja', label: '日本語' },
  { code: 'ko', label: '한국어' },
  { code: 'af', label: 'Afrikaans' },
  { code: 'ak', label: 'Akan' },
  { code: 'sq', label: 'Shqip' },
  { code: 'am', label: 'አማርኛ' },
  { code: 'ar', label: 'العربية' },
  { code: 'hy', label: 'Հայերեն' },
  { code: 'az', label: 'Azərbaycan' },
  { code: 'eu', label: 'Euskara' },
  { code: 'be', label: 'Беларуская' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'bg', label: 'Български' },
  { code: 'my', label: 'မြန်မာ' },
  { code: 'ca', label: 'Català' },
  { code: 'zh-Hans', label: '简体中文' },
  { code: 'hr', label: 'Hrvatski' },
  { code: 'cs', label: 'Čeština' },
  { code: 'da', label: 'Dansk' },
  { code: 'nl', label: 'Nederlands' },
  { code: 'et', label: 'Eesti' },
  { code: 'fil', label: 'Filipino' },
  { code: 'fi', label: 'Suomi' },
  { code: 'fr', label: 'Français' },
  { code: 'gl', label: 'Galego' },
  { code: 'ka', label: 'ქართული' },
  { code: 'de', label: 'Deutsch' },
  { code: 'el', label: 'Ελληνικά' },
  { code: 'gu', label: 'ગુજરાતી' },
  { code: 'ha', label: 'Hausa' },
  { code: 'he', label: 'עברית' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'hu', label: 'Magyar' },
  { code: 'is', label: 'Íslenska' },
  { code: 'id', label: 'Bahasa Indonesia' },
  { code: 'it', label: 'Italiano' },
  { code: 'jv', label: 'Basa Jawa' },
  { code: 'kn', label: 'ಕನ್ನಡ' },
  { code: 'kk', label: 'Қазақ' },
  { code: 'km', label: 'ខ្មែរ' },
  { code: 'rw', label: 'Kinyarwanda' },
  { code: 'lo', label: 'ລາວ' },
  { code: 'lv', label: 'Latviešu' },
  { code: 'lt', label: 'Lietuvių' },
  { code: 'mk', label: 'Македонски' },
  { code: 'ms', label: 'Bahasa Melayu' },
  { code: 'ml', label: 'മലയാളം' },
  { code: 'mr', label: 'मराठी' },
  { code: 'mn', label: 'Монгол' },
  { code: 'ne', label: 'नेपाली' },
  { code: 'nb', label: 'Norsk bokmål' },
  { code: 'fa', label: 'فارسی' },
  { code: 'pl', label: 'Polski' },
  { code: 'pt-BR', label: 'Português (Brasil)' },
  { code: 'pt-PT', label: 'Português (Portugal)' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ' },
  { code: 'ro', label: 'Română' },
  { code: 'ru', label: 'Русский' },
  { code: 'sr', label: 'Српски' },
  { code: 'sd', label: 'سنڌي' },
  { code: 'si', label: 'සිංහල' },
  { code: 'sk', label: 'Slovenčina' },
  { code: 'sl', label: 'Slovenščina' },
  { code: 'es', label: 'Español' },
  { code: 'su', label: 'Basa Sunda' },
  { code: 'sw', label: 'Kiswahili' },
  { code: 'sv', label: 'Svenska' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'te', label: 'తెలుగు' },
  { code: 'th', label: 'ไทย' },
  { code: 'tr', label: 'Türkçe' },
  { code: 'uk', label: 'Українська' },
  { code: 'ur', label: 'اردو' },
  { code: 'uz', label: 'Oʻzbek' },
  { code: 'vi', label: 'Tiếng Việt' },
  { code: 'zu', label: 'isiZulu' },
] as const;

// The model detects the source language itself and has no sourceLanguageCode
// field, so the source picker offers this single sentinel instead of pretending
// the choice reaches the API.
export const GEMINI_AUTO_SOURCE = 'auto';
